# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukafUuWtV4_13WHDT61NnhT2aE8xjgBM
"""

import tkinter as tk
import random

# Thai consonants and their names
thai_consonants = [
    ("ก", "Gor Gai"), ("\u0e02", "Khor Khai"), ("\u0e03", "Khor Khuat"),
    ("\u0e04", "Khor Khwai"), ("\u0e05", "Khor Khon"), ("\u0e06", "Khor Rakhang"),
    ("\u0e07", "Ngor Ngu"), ("\u0e08", "Jor Jan"), ("\u0e09", "Chor Ching"),
    ("\u0e0a", "Chor Chang"), ("\u0e0b", "Sor So"), ("\u0e0c", "Chor Cher"),
]

class FlashcardGame:
    def __init__(self, root):
        self.root = root
        self.root.title("Thai Consonant Flashcards")
        self.root.geometry("400x300")

        self.card_frame = tk.Frame(self.root, bg="white", width=300, height=200)
        self.card_frame.pack(pady=20)

        self.label = tk.Label(self.card_frame, text="", font=("Arial", 48), bg="white")
        self.label.pack(expand=True)

        self.flip_button = tk.Button(self.root, text="Flip", command=self.flip_card)
        self.flip_button.pack()

        self.next_button = tk.Button(self.root, text="Next", command=self.next_card)
        self.next_button.pack()

        self.current_card = None
        self.is_flipped = False
        self.next_card()

    def next_card(self):
        self.current_card = random.choice(thai_consonants)
        self.label.config(text=self.current_card[0])
        self.is_flipped = False

    def flip_card(self):
        if self.current_card and not self.is_flipped:
            self.label.config(text=self.current_card[1])
            self.is_flipped = True
        else:
            self.label.config(text=self.current_card[0])
            self.is_flipped = False

if __name__ == "__main__":
    root = tk.Tk()
    app = FlashcardGame(root)
    root.mainloop()